# Generated by Django 5.2.12 on 2026-04-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="is_on_leave",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
    ]
